version: "3.8"

services:

  # =====================
  # DATABASES
  # =====================

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3308:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # =====================
  # SERVICES
  # =====================

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    depends_on:
      - mysql-inventory
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventory_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql

  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - mysql-order
      - inventory-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/order_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql

  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/product-service

# =====================
# VOLUMES
# =====================

volumes:
  mysql_inventory_data:
  mysql_order_data:
  mongo_data:
