version: "3.8"

services:

  # =====================
  # DISCOVERY SERVER
  # =====================

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"

  # =====================
  # DATABASES
  # =====================

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    ports:
      - "3308:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # =====================
  # SERVICES
  # =====================

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    container_name: inventory-service
    depends_on:
      - discovery-server
      - mysql-inventory
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: inventory-service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventory_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    container_name: order-service
    depends_on:
      - discovery-server
      - mysql-order
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: order-service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/order_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    container_name: product-service
    depends_on:
      - discovery-server
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: product-service
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/product-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka

# =====================
# VOLUMES
# =====================

volumes:
  mysql_inventory_data:
  mysql_order_data:
  mongo_data:
